ARG BASE_IMAGE=node:16.3.0-alpine3.13
FROM ${BASE_IMAGE}

RUN apk add --no-cache \
    dumb-init
ENTRYPOINT ["/usr/bin/dumb-init", "--"]

ARG USER=node
ARG PACKAGE
USER ${USER}

ENV ELASTIC_PORT="9200"
ENV ELASTIC_HOST="host.docker.internal"
ENV ELASTIC_USERNAME=
ENV ELASTIC_PASSWORD=
ENV ELASTIC_PROTOCOL=

ENV ADDRESSR_INDEX_TIMEOUT="30s"
ENV ADDRESSR_INDEX_BACKOFF="1000"
ENV ADDRESSR_INDEX_BACKOFF_INCREMENT="1000"
ENV ADDRESSR_INDEX_BACKOFF_MAX="10000"

WORKDIR "/home/${USER}"

COPY . .

RUN npm install

CMD ["node", "bin/addressr-server-2.js"]
